dist: trusty

#
# julia -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))'

language: node_js

cache:
  apt: true
  directories:
    - $HOME/julia

matrix:
  include:
    - node_js:
        - "6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      before_install:
#        - export CC="gcc-4.9"
#        - export CXX="g++-4.9"
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
        - curl -O 'https://s3.amazonaws.com/julialang/bin/linux/x64/0.5/julia-0.5-latest-linux-x86_64.tar.gz'
        - tar -xzf julia-0.5-latest-linux-x86_64.tar.gz
        - export PATH="${PATH}:${HOME}/julia/bin"
        - export LD_PRELOAD=/home/travis/julia/lib/libjulia.so
        - julia -e 'versioninfo()'
    - os: osx
      node_js:
        - "6"
      before_install:
        - curl -O 'https://s3.amazonaws.com/julialang/bin/osx/x64/0.5/julia-0.5.1-osx10.7+.dmg'
        - hdiutil mount julia-0.5.1-osx10.7+.dmg
        - cp -Ra /Volumes/Julia-0.5.1/*.app/Contents/Resources/julia ~
        - export PATH="${PATH}:${HOME}/julia/bin"
        - julia -e 'versioninfo()'

notifications:
  email: false
