dist: trusty
sudo: false

# Base.DATAROOTDIR
# julia -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))'


language: node_js
node_js:
  - "6"
cache:
  apt: true
before_install:
  - CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
  - mkdir -p ~/julia
  - curl -A "$CURL_USER_AGENT" -s -L --retry 7 'https://s3.amazonaws.com/julialang/bin/linux/x64/0.5/julia-0.5-latest-linux-x86_64.tar.gz' | tar -C ~/julia -x -z --strip-components=1 -f -
  - export PATH="${PATH}:${HOME}/julia/bin"
  - julia -e 'versioninfo()'
  - npm link
  - pwd
  - ls
  - ls node_modules
